name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  python-ci:
    uses: knee5/.github/.github/workflows/python-ci.yml@db36f584df8b0638b85e3ac49b0dbf8702fb7516
    with:
      install-command: python -m pip install -e .
      test-command: python -m unittest
